import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbf9f5",
        "inverse-primary": "#94d3c1",
        "surface-variant": "#e4e2de",
        "primary": "#00342b",
        "primary-fixed-dim": "#94d3c1",
        "surface-container": "#efeeea",
        "on-primary-container": "#7ebdac",
        "on-secondary-fixed": "#360f00",
        "secondary-fixed-dim": "#ffb596",
        "on-secondary": "#ffffff",
        "surface-tint": "#29695b",
        "on-tertiary-fixed": "#241a00",
        "secondary-fixed": "#ffdbcd",
        "inverse-surface": "#30312e",
        "secondary": "#a14009",
        "on-tertiary-fixed-variant": "#574500",
        "on-tertiary-container": "#4f3e00",
        "on-surface": "#1b1c1a",
        "inverse-on-surface": "#f2f0ed",
        "on-secondary-fixed-variant": "#7d2d00",
        "on-primary-fixed-variant": "#065043",
        "error": "#ba1a1a",
        "primary-container": "#004d40",
        "secondary-container": "#fd844c",
        "on-error-container": "#93000a",
        "primary-fixed": "#afefdd",
        "on-error": "#ffffff",
        "on-primary-fixed": "#00201a",
        "outline": "#707975",
        "background": "#fbf9f5",
        "surface-dim": "#dbdad6",
        "on-surface-variant": "#3f4945",
        "surface": "#fbf9f5",
        "error-container": "#ffdad6",
        "on-secondary-container": "#6a2500",
        "outline-variant": "#bfc9c4",
        "tertiary": "#735c00",
        "surface-container-highest": "#e4e2de",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#eae8e4",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#e9c349",
        "on-background": "#1b1c1a",
        "tertiary-container": "#cca730",
        "surface-container-low": "#f5f3ef",
        "tertiary-fixed": "#ffe088",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        gutter: "20px",
        base: "4px",
        xl: "48px",
        lg: "24px",
        xs: "4px",
        md: "16px",
        "sidebar-width": "280px",
      },
      fontFamily: {
        "headline": ['"Source Serif 4"', "serif"],
        "body": ['"IBM Plex Sans Arabic"', "sans-serif"],
        "caption": ['"IBM Plex Sans Arabic"', "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
};

export default config;
